const { contextBridge, ipcRenderer } = require('electron')

contextBridge.exposeInMainWorld('electronAPI', {
  startRandomBattle: () => ipcRenderer.invoke('start-random-battle'),
  makeMove: (move) => ipcRenderer.invoke('make-move', move),
  selectPokemon: (name) => ipcRenderer.invoke('select-pokemon', name),

  on: (channel, cb) => ipcRenderer.on(channel, (event, data) => cb(data)),
  off: (channel) => ipcRenderer.removeAllListeners(channel),
})

/*contextBridge.exposeInMainWorld('electronAPI', {

    startRandomBattle: () => ipcRenderer.invoke('start-random-battle'),
    onPlayer: (cb) => ipcRenderer.on('player', (event, data) => cb(data)),
    offPlayer: () => ipcRenderer.removeAllListeners('player'),
    onSwitch: (cb) => ipcRenderer.on('switch', (event, data) => cb(data)),
    offSwitch: () => ipcRenderer.removeAllListeners('switch'),
    onTeam: (cb) => ipcRenderer.on('team', (event, data) => cb(data)),
    offTeam: () => ipcRenderer.removeAllListeners('team'),
    makeMove: (move) => ipcRenderer.invoke('make-move', move),
    onForceSwitch: (cb) => ipcRenderer.on('forceSwitch',(event,data)=>cb(data)),
    offForceSwitch: () => ipcRenderer.removeAllListeners('forceSwitch'),
    onWait: (cb) => ipcRenderer.on('wait',(event,data)=>cb(data)),
    offWait: () => ipcRenderer.removeAllListeners('wait'),
    onFaint: (cb) => ipcRenderer.on('faint',(event,data)=>cb(data)),
    offFaint: () => ipcRenderer.removeAllListeners('faint'),
    onMove: (cb) => ipcRenderer.on('move',(event,data)=>cb(data)),
    offMove: () => ipcRenderer.removeAllListeners('move'),
    onDamage: (cb) => ipcRenderer.on('damage',(event,data)=>cb(data)),
    offDamage: () => ipcRenderer.removeAllListeners('damage'),
    onStatus: (cb) => ipcRenderer.on('status',(event,data)=>cb(data)),
    offStatus: () => ipcRenderer.removeAllListeners('status'),
    onStatusRecover: (cb) => ipcRenderer.on('statusRecover',(event,data)=>cb(data)),
    offStatusRecover: () => ipcRenderer.removeAllListeners('statusRecover'),
    onHeal: (cb) => ipcRenderer.on('heal',(event,data)=>cb(data)),
    offHeal: () => ipcRenderer.removeAllListeners('heal'),
    onCrit: (cb) => ipcRenderer.on('crit',(event,data)=>cb(data)),
    offCrit: () => ipcRenderer.removeAllListeners('crit'),
    onSuperEffective: (cb) => ipcRenderer.on('superEffective',(event,data)=>cb(data)),
    offSuperEffective: () => ipcRenderer.removeAllListeners('superEffective'),
    onResisted: (cb) => ipcRenderer.on('resisted',(event,data)=>cb(data)),
    offResisted: () => ipcRenderer.removeAllListeners('resisted'),
    selectPokemon: (pokemonName) => ipcRenderer.invoke('select-pokemon', pokemonName),
    onMiss: (cb) => ipcRenderer.on('miss',(event,data)=>cb(data)),
    offMiss: () => ipcRenderer.removeAllListeners('miss'),
    onEndItem: (cb) => ipcRenderer.on('enditem',(event,data)=>cb(data)),
    offEndItem: () => ipcRenderer.removeAllListeners('enditem'),
    onReplace: (cb) => ipcRenderer.on('replace', (event, data) => cb(data)),
    offReplace: () => ipcRenderer.removeAllListeners('replace'),
    onStartVolatile: (cb) => ipcRenderer.on('startVolatile', (event, data) => cb(data)),
    offStartVolatile: () => ipcRenderer.removeAllListeners('startVolatile'),
    onEndVolatile: (cb) => ipcRenderer.on('endVolatile', (event, data) => cb(data)),
    offEndVolatile: () => ipcRenderer.removeAllListeners('endVolatile'),
    onImmune: (cb) => ipcRenderer.on('immune',(event,data)=>cb(data)),
    offImmune: () => ipcRenderer.removeAllListeners('immune'),
    onBattleEnd: (cb) => ipcRenderer.on('battleEnd',(event,data)=>cb(data)),
    offBattleEnd: () => ipcRenderer.removeAllListeners('battleEnd'),
    onCant: (cb) => ipcRenderer.on('cant',(event,data)=>cb(data)),
    offCant: () => ipcRenderer.removeAllListeners('cant'),
    onStartSideCondition: (cb) => ipcRenderer.on('startSideCondition',(event,data)=>cb(data)),
    offStartSideCondition: () => ipcRenderer.removeAllListeners('startSideCondition'),
    onClearAllBoost: (cb) => ipcRenderer.on('clearAllBoost',(event,data)=>cb(data)),
    offClearAllBoost: () => ipcRenderer.removeAllListeners('clearAllBoost'),
    onFail: (cb) => ipcRenderer.on('fail',(event,data)=>cb(data)),
    offFail: () => ipcRenderer.removeAllListeners('fail'),

});*/