const MENSAJES = {
    'psn': '¡{pkm} ha sido envenenado!',
    'tox': '¡{pkm} ha sido gravemente envenenado!',
    'brn': '¡{pkm} ha sido quemado!',
    'par': '¡{pkm} ha sido paralizado!',
    'slp': '¡{pkm} ha caído dormido!',
    'frz': '¡{pkm} ha sido congelado!',
    'psn-recover': '¡{pkm} se ha curado del envenenamiento!',
    'tox-recover': '¡{pkm} se ha curado del envenenamiento!',
    'brn-recover': '¡{pkm} se ha curado de la quemadura!',
    'par-recover': '¡{pkm} ya no está paralizado!',
    'slp-recover': '¡{pkm} ha despertado!',
    'frz-recover': '¡{pkm} se ha descongelado!',
    '[confusion]-start': '¡{pkm} se ha confundido!',
    '[move: Leech Seed]-start': '¡{pkm} ha sido infectado por drenadoras!',
    '[Substitute]-start': '{pkm} ha creado un sustituto',
    '[move: Taunt]-start': '¡{pkm} cayó en la provocación!',
    '[Attract]-start': '¡{pkm} se ha enamorado!',
    '[confusion]-end': '¡{pkm} ya no está confundido!',
    '[Substitute]-end': '¡El sustituto de {pkm} se ha roto!',
    'winner-p1': '¡Has ganado el combate!',
    'winner-p2': '¡Has perdido el combate!',
    'winner': '¡{winner} ha ganado el combate!',
    'cant-[slp]': '¡{pkm} está dormido!',
    'cant-[par]': '¡{pkm} está paralizado, ¡no se puede mover!',
    'cant-[frz]': '¡{pkm} está congelado, ¡no se puede mover!',
    'cant-[ability: Truant]': '¡{pkm} se rasca la cabeza!',
    'cant-[move: Taunt]': '¡{pkm} no puede usar movimientos de estado!',
    'cant-[flinch]': '¡{pkm} ha retrocedido!',
    'cant-[nopp]': '¡{pkm} no tiene suficientes pp!',
    'cant-[recharge]': '¡{pkm} necesita recuperar energía!',
    'cant-[Attract]': '¡{pkm} se duerme en los laureles por el enamoramiento!',
    'side-condition-[Toxic Spikes]': '¡{pkm} ha sido rodeado por púas tóxicas!',
    'side-condition-[Stealth Rock]': '¡{pkm} ha sido rodeado por rocas afiladas!',
    'side-condition-[Spikes]': '¡{pkm} ha sido rodeado por púas!',
    'side-condition-[Sticky Web]': '¡{pkm} ha sido rodeado por una telaraña pegajosa!',
    'side-condition-[Reflect]': '¡{pkm} ha creado un muro de luz!',
    'side-condition-[Light Screen]': '¡{pkm} ha creado un pantalla de luz!',
    'side-condition-[Aurora Veil]': '¡{pkm} ha creado un velo de aurora!',
    'side-condition-[Safeguard]': '¡{pkm} ha creado un resguardo para su equipo!',
    'side-condition-[Tailwind]': '¡{pkm} ha creado un viento a favor para su equipo!',
    'side-condition-end-[Reflect]': '¡El muro de luz de {pkm} ha desaparecido!',
    'side-condition-end-[Light Screen]': '¡La pantalla de luz de {pkm} ha desaparecido!',
    'side-condition-end-[Aurora Veil]': '¡El velo aurora de {pkm} ha desaparecido!',
    'side-condition-end-[Safeguard]': '¡El velo sagrado de {pkm} ha desaparecido!',
    'side-condition-end-[Tailwind]': '¡El viento a favor de {pkm} ha desaparecido!',
    'clear-all-boost': '¡Todos los cambios de características han desaparecido!',
    'effect-[confusion]': '¡{pkm} está confundido!',
    'effect-[move: Protect]': '¡{pkm} se ha protegido!',
    'effect-[move: Sticky Web]': '¡{pkm} ha caido sobre telaraña pegajosa!',
    'effect-[move: Struggle]': '¡A {pkm} no le quedan movimientos!',
    'effect-[move: Heal Bell]': '¡El equipo de {pkm} ha sido curado de problemas de estado!',
    'effect-[move: Trick]': '¡{pkm} ha intercambiado objetos!',
    'effect-[move: Substitute]': '¡El sustituto de {pkm} ha recibido daño en su lugar!',
    'effect-[move: Fire Spin]': '¡{pkm} ha recibido daño por un vórtice de fuego!',
    'effect-[move: Attract]': '¡{pkm} está enamorado!',
    'effect-[ability: Mummy]': '¡{pkm} ha adquirido la habilidad: Momia!',
    'effect-[trapped]': '¡{pkm} no puede escapar!',
    'effect-[Skill Swap]': '¡{pkm} ha intercambiado las habilidades!',
    'effect-[item: Quick Claw]': '¡{pkm} se mueve primero gracias a su Garra Rápida!',
    'boost-atk-[1]': '¡El ataque de {pkm} ha aumentado!',
    'boost-spa-[1]': '¡El ataque especial de {pkm} ha aumentado!',
    'boost-def-[1]': '¡La defensa de {pkm} ha aumentado!',
    'boost-spd-[1]': '¡La defensa especial de {pkm} ha aumentado!',
    'boost-spe-[1]': '¡La velocidad de {pkm} ha aumentado!',
    'boost-atk-[2]': '¡El ataque de {pkm} ha aumentado mucho!',
    'boost-spa-[2]': '¡El ataque especial de {pkm} ha aumentado mucho!',
    'boost-def-[2]': '¡La defensa de {pkm} ha aumentado mucho!',
    'boost-spd-[2]': '¡La defensa especial de {pkm} ha aumentado mucho!',
    'boost-spe-[2]': '¡La velocidad de {pkm} ha aumentado mucho!',
    'boost-atk-[6]': '¡El ataque de {pkm} ha aumentado al máximo!',
    'boost-atk-[0]': '¡El ataque de {pkm} no puede subir más!',
    'boost-spa-[0]': '¡El ataque especial de {pkm} no puede subir más!',
    'boost-def-[0]': '¡La defensa de {pkm} no puede subir más!',
    'boost-spd-[0]': '¡La defensa especial de {pkm} no puede subir más!',
    'boost-spe-[0]': '¡La velocidad de {pkm} no puede subir más!',
    'boost-evasion-[1]': '¡La evasión de {pkm} ha aumentado!',
    'boost-evasion-[0]': '¡La evasión de {pkm} no puede subir más!',
    'boost-accuracy-[1]': '¡La precisión de {pkm} ha aumentado!',
    'boost-accuracy-[0]': '¡La precisión de {pkm} no puede subir más!',
    'prepare-[Fly]': '¡{pkm} se ha elevado en el aire!',
    'prepare-[Dive]': '¡{pkm} se ha sumergido en el agua!',
    'prepare-[Dig]': '¡{pkm} se ha enterrado en el suelo!',
    'prepare-[Sky Attack]': '¡{pkm} está brillando!',
    'prepare-[Solar Beam]': '¡{pkm} está cargando energía!',
    'prepare-[Skull Bash]': '¡{pkm} ha bajado su cabeza!',
    'damage-[confusion]': '¡{pkm} se ha golpeado a si mismo!',
    'damage-[Leech Seed]': '¡La energía de {pkm} está siendo drenada!',
    'damage-[Stealth Rock]': '¡Las rocas afiladas han dañado a {pkm}!',
    'damage-[Recoil]': '¡{pkm} ha recibido daño de retroceso!',
    'damage-[ability: Rough Skin]': '¡{pkm} ha recibido daño de contacto!',
    'damage-[item: Rocky Helmet]': '¡{pkm} se ha golpeado con un casco muy duro!',
    'damage-[Sandstorm]': '¡{pkm} es golpeado fuertemente por la tormenta de arena!',
    'damage-[Hail]': '¡{pkm} es golpeado fuertemente por el granizo!',
    'damage-[move: Sand Tomb]': '¡{pkm} es golpeado por un bucle de arena!',
    'damage-[Curse]': '¡{pkm} sufre por la maldición!',
    'damage-[psn]': '¡{pkm} sufre por el veneno!',
    'damage-[brn]': '¡{pkm} sufre por la quemadura!',
    'damage-[ability: Solar Power]': '¡La radiación solar desgasta a {pkm}!',
    'damage-[ability: Iron Barbs]': '¡Las púas de hierro dañan a {pkm}!',
    'damage-[move: Fire Spin]': '¡{pkm} ha recibido daño por un vórtice de fuego!',
    'weather-[RainDance]': '¡Ha empezado a llover!',
    'weather-[none]': 'El clima ha vuelto a la normalidad.',
    'upkeep-[RainDance]': '¡Está cayendo un palo de agua!',
    'weather-[Sandstorm]': '¡Ha empezado un tormenta de arena!',
    'upkeep-[Sandstorm]': '¡La arena es tanta que no permite ver!',
    'upkeep-[Hail]': '¡Está cayendo granizo!',
    'weather-[Hail]': '¡Ha empezado a granizar!',
    'upkeep-[SunnyDay]': '¡El sol brilla intensamente!',
    'weather-[SunnyDay]': '¡El sol ha salido!'

}
export default MENSAJES;