const MENSAJES = {
    'psn': 'ha sido envenenado!',
    'tox': 'ha sido gravemente envenenado!',
    'brn': 'ha sido quemado!',
    'par': 'ha sido paralizado!',
    'slp': 'ha caído dormido!',
    'frz': 'ha sido congelado!',
    'psn-recover': 'se ha curado del envenenamiento!',
    'tox-recover': 'se ha curado del envenenamiento!',
    'brn-recover': 'se ha curado de la quemadura!',
    'par-recover': 'ya no está paralizado!',
    'slp-recover': 'ha despertado!',
    'frz-recover': 'se ha descongelado!',
    '[confusion]-start': '¡{pkm} se ha confundido!',
    '[move: Leech Seed]-start': '¡{pkm} ha sido infectado por drenadoras!',
    '[Substitute]-start': '{pkm} ha creado un sustituto',
    '[move: Taunt]-start': '¡{pkm} cayó en la provocación!',
    '[confusion]-end': '¡{pkm} ya no está confundido!',
    '[Substitute]-end': '¡El sustituto de {pkm} se ha roto!',
    'winner-p1': '¡Has ganado el combate!',
    'winner-p2': '¡Has perdido el combate!',
    'winner': '¡{winner} ha ganado el combate!',
    'cant-[slp]': '¡{pkm} está dormido!',
    'cant-[par]': '¡{pkm} está paralizado, ¡no se puede mover!',
    'cant-[frz]': '¡{pkm} está congelado, ¡no se puede mover!',
    'cant-[ability: Truant]': '¡{pkm} se rasca la cabeza!',
    'cant-[move: Taunt]': '¡{pkm} no puede usar movimientos de estado!',
    'cant-[flinch]': '¡{pkm} ha retrocedido!',
    'cant-[nopp]': '¡{pkm} no tiene suficientes pp!',
    'cant-[recharge]': '¡{pkm} necesita recuperar energía!',
    'side-condition-[Toxic Spikes]': '¡{pkm} ha sido rodeado por púas tóxicas!',
    'side-condition-[Stealth Rock]': '¡{pkm} ha sido rodeado por rocas afiladas!',
    'side-condition-[Spikes]': '¡{pkm} ha sido rodeado por púas!',
    'side-condition-[Sticky Web]': '¡{pkm} ha sido rodeado por una telaraña pegajosa!',
    'side-condition-[Reflect]': '¡{pkm} ha creado un muro de luz!',
    'side-condition-[Light Screen]': '¡{pkm} ha creado un pantalla de luz!',
    'side-condition-[Aurora Veil]': '¡{pkm} ha creado un velo de aurora!',
    'side-condition-[Safeguard]': '¡{pkm} ha creado un resguardo para su equipo!',
    'side-condition-end-[Reflect]': '¡El muro de luz de {pkm} ha desaparecido!',
    'side-condition-end-[Light Screen]': '¡La pantalla de luz de {pkm} ha desaparecido!',
    'side-condition-end-[Aurora Veil]': '¡El velo aurora de {pkm} ha desaparecido!',
    'side-condition-end-[Safeguard]': '¡El velo sagrado de {pkm} ha desaparecido!',
    'clear-all-boost': '¡Todos los cambios de características han desaparecido!',
    'effect-[confusion]': '¡{pkm} está confundido!',
    'effect-[move: Protect]': '¡{pkm} se ha protegido!',
    'effect-[move: Sticky Web]': '¡{pkm} ha caido sobre telaraña pegajosa!',
    'effect-[move: Struggle]': '¡A {pkm} no le quedan movimientos!',
    'effect-[move: Heal Bell]': '¡El equipo de {pkm} ha sido curado de problemas de estado!',
    'effect-[move: Trick]': '¡{pkm} ha intercambiado objetos!',
    'effect-[move: Substitute]': '¡El sustituto de {pkm} ha recibido daño en su lugar!',
    'effect-[move: Fire Spin]': '¡{pkm} ha recibido daño por un vórtice de fuego!',
    'effect-[ability: Mummy]': '¡{pkm} ha adquirido la habilidad: Momia!',
    'boost-atk-[1]': '¡El ataque de {pkm} ha aumentado!',
    'boost-spa-[1]': '¡El ataque especial de {pkm} ha aumentado!',
    'boost-def-[1]': '¡La defensa de {pkm} ha aumentado!',
    'boost-spd-[1]': '¡La defensa especial de {pkm} ha aumentado!',
    'boost-spe-[1]': '¡La velocidad de {pkm} ha aumentado!',
    'boost-atk-[2]': '¡El ataque de {pkm} ha aumentado mucho!',
    'boost-spa-[2]': '¡El ataque especial de {pkm} ha aumentado mucho!',
    'boost-def-[2]': '¡La defensa de {pkm} ha aumentado mucho!',
    'boost-spd-[2]': '¡La defensa especial de {pkm} ha aumentado mucho!',
    'boost-spe-[2]': '¡La velocidad de {pkm} ha aumentado mucho!',
    'boost-atk-[6]': '¡El ataque de {pkm} ha aumentado al máximo!',
    'boost-evasion-[1]': '¡La evasión de {pkm} ha aumentado!',
    'prepare-[Fly]': '¡{pkm} se ha elevado en el aire!',
    'prepare-[Dive]': '¡{pkm} se ha sumergido en el agua!',
    'prepare-[Dig]': '¡{pkm} se ha enterrado en el suelo!',
    'prepare-[Sky Attack]': '¡{pkm} está brillando!',
    'prepare-[Solar Beam]': '¡{pkm} está cargando energía!'


}
export default MENSAJES;